# Generated by Django 2.2.1 on 2019-06-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('technologie', models.CharField(blank=True, max_length=20)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
